name = "v-arshia10"
main = "src/index.js"
compatibility_date = "2024-01-01"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "7f2e21b3-f8b1-41dd-a263-174b463fb603"
# TROJAN_PASSWORD = "your-trojan-password"  # Optional: If not set, UUID will be used as password
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
